# Generated by Django 6.0.3 on 2026-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
    ]
