# Generated by Django 6.0.3 on 2026-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_bio_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('answers', models.JSONField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=models.CASCADE, related_name='quiz_attempts', to='course.course')),
                ('student_profile', models.ForeignKey(on_delete=models.CASCADE, related_name='quiz_attempts', to='student.studentprofile')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
