# Generated by Django 6.0.3 on 2026-06-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_add_enrollment_progress_and_quiz_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='highest_quiz_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='highest_quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
