# Generated by Django 6.0.6 on 2026-06-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentcourseenrollment_highest_quiz_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='highest_quiz_grade',
            new_name='recent_quiz_grade',
        ),
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='highest_quiz_score',
            new_name='recent_quiz_score',
        ),
    ]
