# Generated by Django 6.0.3 on 2026-05-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
