# Generated by Django 6.0.3 on 2026-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_lessoncontent_studentlessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='material_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('material', 'Material')], max_length=10),
        ),
    ]
