# Generated by Django 6.0.3 on 2026-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_thumbnail_url_lessoncontent_material_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
