# Generated by Django 6.0.3 on 2026-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_thumbnail_url_course_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
