# Generated by Django 6.0.3 on 2026-05-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_thumbnail_image_course_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='material_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='LessonContent',
        ),
    ]
