# Generated by Django 6.0.3 on 2026-06-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_lesson_description_lesson_material_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='material_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
