# Generated by Django 6.0.3 on 2026-06-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0008_remove_course_thumbnail_url_and_more'),
    ]

    operations = [
        # Important: This migration is intended to fix the MySQL IntegrityError
        # "Field 'lesson_type' doesn't have a default value" by removing the
        # legacy column from the underlying lesson table.
        #
        # If the column already doesn't exist in your DB, you may need to
        # manually reconcile or edit this migration.
        migrations.RunSQL(
            sql="ALTER TABLE course_lesson DROP COLUMN lesson_type;",
            reverse_sql="ALTER TABLE course_lesson ADD COLUMN lesson_type varchar(20) NOT NULL DEFAULT 'video';",
        ),
    ]

