# Generated by Django 6.0.3 on 2026-06-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0009_remove_lesson_type_from_lesson'),
    ]

    operations = [
        # MySQL cannot set a DEFAULT for TEXT/BLOB columns.
        # The error "Field 'content_text' doesn't have a default value"
        # happens when Django tries to INSERT without providing content_text.
        # Making the column NULLable (and defaulting Django to empty string)
        # prevents the DB integrity error.
        migrations.RunSQL(
            sql="ALTER TABLE course_lesson MODIFY content_text longtext NULL;",
            reverse_sql="ALTER TABLE course_lesson MODIFY content_text longtext NOT NULL;",
        ),
    ]

