# Generated by Django 6.0.3 on 2026-06-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0009_remove_lesson_type_from_lesson'),
    ]

    operations = [
        # No-op: MySQL cannot set DEFAULT for TEXT/BLOB columns.
        # Kept as a stub for migration history.
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql="SELECT 1;",
        ),

    ]

