# Generated by Django 6.0.3 on 2026-06-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_set_content_text_default_on_lesson'),
        ('course', '0010a_make_content_text_nullable'),
    ]

    operations = [
    ]
